name: Tailscale Exit Node (TEST)

on:
  workflow_dispatch:

jobs:
  tailscale:
    runs-on: ubuntu-latest
    steps:
      - name: Install and connect Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up \
            --authkey=tskey-auth-kerErdn2gE11CNTRL-wz8tLhnDs2216hcK4A3m22mmcbRaPkfWg \
            --hostname=gh-runner \
            --advertise-exit-node
          sleep 6h
